genes: ["HA1", "HA2"]

reference_name: "MW626062.1"

build_dir: "results/flu_h1n1pdm_ha"
dataset_dir: "datasets/flu_h1n1pdm_ha"

sequences: "data/flu_h1n1pdm_ha/sequences.fasta"
example_data: "data/flu_h1n1pdm_ha/example_data.fasta"
metadata: "data/flu_h1n1pdm_ha/metadata.tsv"
reference: "profiles/flu_h1n1pdm_ha/reference.fasta"
annotation: "profiles/flu_h1n1pdm_ha/annotation.gff"
auspice_config: "profiles/flu_h1n1pdm_ha/auspice_config.json"
clades: "data/flu_h1n1pdm_ha/clades.tsv"

refine_options: "--root best --timetree --keep-polytomies"
