genes: ["pro", "RT-p66", "RT-p51", "INT",
        "p17", "p24", "p2", "p7", "p1", "p6",
        "vif", "vpr", "tat",  "rev", "vpu","gp120", "gp41", "nef"]

sequences: "data/HIV-1/sequences.fasta"
metadata: "data/HIV-1/metadata.tsv"
reference: "profiles/HIV-1/reference.fasta"
annotation: "profiles/HIV-1/annotation.gff"
auspice_config: "profiles/HIV-1/auspice_config.json"
build_dir: "results/HIV-1"
qc_json:  "profiles/HIV-1/qc.json"
dataset_dir: "datasets/HIV-1"


